import { defineCollection, z } from "astro:content";
import { glob } from "astro/loaders";

/**
 * Generated by `npm run import` from the material. Schema failures break the
 * build on purpose: a topic without a title or with an unknown origin means the
 * importer or the source drifted (ADR-002).
 */
const topics = defineCollection({
  loader: glob({ pattern: "**/*.md", base: "./src/content/topics" }),
  schema: z.object({
    title: z.string(),
    /** "15.3" for imported topics, empty for pages written for this site. */
    sectionNumber: z.string(),
    category: z.string(),
    order: z.number().int().positive(),
    cardCount: z.number().int().nonnegative(),
    sourceFile: z.string().optional(),
    origin: z.enum(["material", "new"]).default("material"),
    flags: z.array(z.enum(["degisken", "emin-degil"])).default([]),
    /** Sources are required for pages written outside the material. */
    sources: z.array(z.object({ label: z.string(), url: z.string().url() })).default([]),
  }),
});

const categories = defineCollection({
  loader: glob({ pattern: "*.md", base: "./src/content/categories" }),
  schema: z.object({
    category: z.string(),
    sourceFiles: z.array(z.string()).default([]),
  }),
});

// One JSON per category; the entry id is the category slug.
const quizzes = defineCollection({
  loader: glob({ pattern: "*.json", base: "./src/content/quizzes" }),
  schema: z.object({
    category: z.string(),
    source: z.string(),
    items: z.array(z.object({ n: z.number(), question: z.string(), answer: z.string() })),
  }),
});

export const collections = { topics, categories, quizzes };
