import { defineCollection, z } from "astro:content";
import { glob } from "astro/loaders";

/**
 * Generated by `npm run import` from the material. Schema failures break the
 * build on purpose: a topic without a title or with an unknown origin means the
 * importer or the source drifted (ADR-002).
 */
const topics = defineCollection({
  loader: glob({ pattern: "**/*.md", base: "./src/content/topics" }),
  schema: z.object({
    title: z.string(),
    /** "15.3" for imported topics, empty for pages written for this site. */
    sectionNumber: z.string(),
    category: z.string(),
    order: z.number().int().positive(),
    cardCount: z.number().int().nonnegative(),
    sourceFile: z.string().optional(),
    origin: z.enum(["material", "new"]).default("material"),
    flags: z.array(z.enum(["degisken", "emin-degil"])).default([]),
    /** Sources are required for pages written outside the material. */
    sources: z.array(z.object({ label: z.string(), url: z.string().url() })).default([]),
  }),
});

const categories = defineCollection({
  loader: glob({ pattern: "*.md", base: "./src/content/categories" }),
  schema: z.object({
    category: z.string(),
    sourceFiles: z.array(z.string()).default([]),
  }),
});

// One JSON per category; the entry id is the category slug.
const quizzes = defineCollection({
  loader: glob({ pattern: "*.json", base: "./src/content/quizzes" }),
  schema: z.object({
    category: z.string(),
    source: z.string(),
    items: z.array(z.object({ n: z.number(), question: z.string(), answer: z.string() })),
  }),
});

/**
 * Hand-written lessons (ADR-015). They live outside src/content/ on purpose:
 * that folder is generated and `import:check` guards it. A lesson is matched to
 * an imported step by file path — `web-temelleri/istemci-sunucu-modeli.mdx`
 * replaces the term-card view of that step. `_index.mdx` is the category landing.
 */
const lessons = defineCollection({
  loader: glob({ pattern: "**/*.mdx", base: "./src/lessons" }),
  schema: z.object({
    /** One-sentence promise shown under the title and in link previews. */
    summary: z.string(),
    /** "Bu derste öğreneceklerin" — what the reader can do afterwards. */
    outcomes: z.array(z.string()).default([]),
    minutes: z.number().int().positive().optional(),
    /** Primary sources; a lesson without one does not build (CLAUDE.md rule 4). */
    sources: z.array(z.object({ label: z.string(), url: z.string().url() })).min(1),
    /** Facts that are not in the material — listed on the page and in the round report. */
    additions: z.array(z.string()).default([]),
    flags: z.array(z.enum(["degisken", "emin-degil"])).default([]),
    /** Ordinary words this lesson means as glossary terms ("card", "table"); see rehype-term-refs. */
    includeTerms: z.array(z.string()).default([]),
    /** Words whose shared definition is the wrong one here ("header" in page anatomy). */
    skipTerms: z.array(z.string()).default([]),
  }),
});

export const collections = { topics, categories, quizzes, lessons };
